# 1. Cài thư viện

In [28]:
!pip install duckdb pandas numpy scikit-learn statsmodels pmdarima python-dotenv

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (0.14.6)
Requirement already satisfied: pmdarima in /usr/local/lib/python3.12/dist-packages (2.1.1)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (26.2)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /usr/local/lib/python3.12/dist-packages (from pmdarima) (3.0.12)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from pmdarima) (2.5.0)
Requirement already satisfied: setuptools!=50.0.0,>=42 in /usr/local/lib/python3.12/dist-packages (from pmdarima) (75.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# 2. Import thư viện

In [29]:
import duckdb
import pandas as pd
import numpy as np

from dotenv import load_dotenv

from statsmodels.tsa.stattools import adfuller
from pmdarima import auto_arima

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error
)

# 3. Kết nối MotherDuck

In [38]:
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhbmxnMjM0MTZAc3QudWVsLmVkdS52biIsIm1kUmVnaW9uIjoiYXdzLXVzLWVhc3QtMSIsInNlc3Npb24iOiJ2YW5sZzIzNDE2LnN0LnVlbC5lZHUudm4iLCJwYXQiOiI2eUNGTFdnQVNJS05KbVY1VXJIUm10Tm56cnZlbUhYcDJVQ0lMSFBuWDg0IiwidXNlcklkIjoiNWQxN2FjNzgtMmNhNS00ZmI5LWJmNzAtZjAzMGYzOGMxNTAzIiwiaXNzIjoibWRfcGF0IiwicmVhZE9ubHkiOmZhbHNlLCJ0b2tlblR5cGUiOiJyZWFkX3dyaXRlIiwiaWF0IjoxNzc5OTU4NDcyfQ.8eKwU6C611LqAu6WEVw37tCcGY2hZUdm8M1zvl_Iz7A"

conn = duckdb.connect(
    f"md:agri_dwh?motherduck_token={TOKEN}"
)

import duckdb

# 4. Load dữ liệu

In [40]:
df = conn.execute("""
    SELECT *
    FROM gold.gold_ml_features
    WHERE commodity IN ('rice', 'coffee', 'pepper')
    ORDER BY commodity, price_date
""").fetchdf()

df.head()

,price_date,commodity,year,quarter,month,week,is_weekend,is_vietnam_public_holiday,is_harvest_season,price_usd_per_kg,price_change_pct,price_7d_avg,price_30d_avg,price_90d_avg,price_30d_volatility,price_lag_1,price_lag_7,price_lag_30,source_count
0,2015-01-01,coffee,2015,1,1,1,False,True,True,1.66580,NaN,1.665800,1.665800,1.665800,NaN,NaN,NaN,NaN,1
1,2015-02-01,coffee,2015,1,2,5,True,False,False,1.65828,-0.451435,1.662040,1.662040,1.662040,0.005317,1.66580,NaN,NaN,1
2,2015-03-01,coffee,2015,1,3,9,True,False,False,1.71194,3.235883,1.678673,1.678673,1.678673,0.029054,1.65828,NaN,NaN,1
3,2015-04-01,coffee,2015,2,4,14,False,False,False,1.70027,-0.681683,1.684073,1.684073,1.684072,0.026065,1.71194,NaN,NaN,1
4,2015-05-01,coffee,2015,2,5,18,False,True,False,1.64906,-3.011875,1.677070,1.677070,1.677070,0.027472,1.70027,NaN,NaN,1

# 5. Chuyển kiểu ngày và sắp xếp

In [41]:
df["price_date"] = pd.to_datetime(df["price_date"])

df = df.sort_values(
    ["commodity", "price_date"]
)

# 6. Tạo target_price

In [42]:
df["target_price"] = (
    df.groupby("commodity")["price_usd_per_kg"]
      .shift(-1)
)

df = df.dropna(
    subset=["target_price"]
)

# 7. Kiểm tra target

In [43]:
df[
    [
        "price_date",
        "commodity",
        "price_usd_per_kg",
        "target_price"
    ]
].head(10)

  price_date commodity  price_usd_per_kg  target_price
0 2015-01-01    coffee           1.66580       1.65828
1 2015-02-01    coffee           1.65828       1.71194
2 2015-03-01    coffee           1.71194       1.70027
3 2015-04-01    coffee           1.70027       1.64906
4 2015-05-01    coffee           1.64906       1.71476
5 2015-06-01    coffee           1.71476       1.67237
6 2015-07-01    coffee           1.67237       1.77666
7 2015-08-01    coffee           1.77666       1.74754
8 2015-09-01    coffee           1.74754       1.71905
9 2015-10-01    coffee           1.71905       1.62762

# 8. Kiểm tra kích thước dữ liệu

In [44]:
df.shape

(357, 20)

# 9. Data Quality Summary

In [45]:
summary = (
    df.groupby("commodity")
      .agg(
          min_date=("price_date", "min"),
          max_date=("price_date", "max"),
          rows=("price_date", "count"),
          missing_price=("price_usd_per_kg",
                         lambda s: s.isna().sum()),
          avg_price=("price_usd_per_kg", "mean")
      )
)

summary

            min_date   max_date  rows  missing_price  avg_price
commodity
coffee    2015-01-01 2024-11-01   119              0   2.038196
pepper    2015-01-01 2024-11-01   119              0   4.450982
rice      2015-01-01 2024-11-01   119              0   0.431984

# 10. Kiểm tra missing values

In [46]:
df.isnull().sum()

price_date                    0
commodity                     0
year                          0
quarter                       0
month                         0
week                          0
is_weekend                    0
is_vietnam_public_holiday     0
is_harvest_season             0
price_usd_per_kg              0
price_change_pct              3
price_7d_avg                  0
price_30d_avg                 0
price_90d_avg                 0
price_30d_volatility          3
price_lag_1                   3
price_lag_7                  21
price_lag_30                 90
source_count                  0
target_price                  0
dtype: int64

# 11. Kiểm tra phân chia dữ liệu

In [47]:
train_df = df[
    df["price_date"] < "2023-01-01"
]

val_df = df[
    (df["price_date"] >= "2023-01-01")
    &
    (df["price_date"] < "2024-01-01")
]

test_df = df[
    (df["price_date"] >= "2024-01-01")
    &
    (df["price_date"] < "2025-01-01")
]

# 12. Kiểm tra số dòng

In [48]:
print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

Train: 288
Validation: 36
Test: 33

# 13. Hàm đánh giá

In [49]:
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    mean_absolute_percentage_error
)

import numpy as np

In [50]:
def evaluate_model(y_true, y_pred):

    rmse = np.sqrt(
        mean_squared_error(y_true, y_pred)
    )

    mae = mean_absolute_error(
        y_true,
        y_pred
    )

    mape = (
        mean_absolute_percentage_error(
            y_true,
            y_pred
        ) * 100
    )

    return rmse, mae, mape

# 14. Chạy ARIMA cho cả 3 mặt hàng

In [64]:
results = []

forecast_list = []

commodities = [
    "coffee",
    "rice",
    "pepper"
]

for commodity in commodities:

    train_data = train_df[
        train_df["commodity"] == commodity
    ]

    test_data = pd.concat([
        val_df[val_df["commodity"] == commodity],
        test_df[test_df["commodity"] == commodity]
    ])

    model = auto_arima(
        train_data["price_usd_per_kg"],
        seasonal=False,
        suppress_warnings=True
    )

    forecast = model.predict(
        n_periods=len(test_data)
    )

    rmse, mae, mape = evaluate_model(
        test_data["price_usd_per_kg"],
        forecast
    )

    results.append({
        "commodity": commodity,
        "arima_order": str(model.order),
        "rmse": rmse,
        "mae": mae,
        "mape": mape
    })

    forecast_temp = pd.DataFrame({
        "date": test_data["price_date"].values,
        "commodity": commodity,
        "actual_price": test_data["price_usd_per_kg"].values,
        "predicted_price": forecast
    })

    forecast_list.append(
        forecast_temp
    )

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

# 15. Bảng kết quả metric

In [61]:
metrics_df = pd.DataFrame(results)

metrics_df

  commodity arima_order      rmse       mae       mape
0    coffee   (0, 1, 0)  1.299288  1.112294  30.535434
1      rice   (0, 1, 0)  0.139201  0.137992  24.846247
2    pepper   (0, 1, 0)  0.601002  0.494289  10.868928

# 16. Gom toàn bộ forecast

In [62]:
forecast_df = pd.concat(
    forecast_list,
    ignore_index=True
)

forecast_df.head()

        date commodity  actual_price  predicted_price
0 2023-01-01    coffee       2.62211          2.22929
1 2023-02-01    coffee       2.69114          2.22929
2 2023-03-01    coffee       2.60539          2.22929
3 2023-04-01    coffee       2.66971          2.22929
4 2023-05-01    coffee       2.85136          2.22929

# 17. Kiểm tra kích thước forecast

In [63]:
forecast_df.shape

(69, 4)

# 18. Tạo bảng forecast_arima

In [65]:
conn.execute("""
CREATE TABLE IF NOT EXISTS gold.forecast_arima (
    date DATE,
    commodity VARCHAR,
    actual_price DOUBLE,
    predicted_price DOUBLE
)
""")

# 19. Xóa dữ liệu cũ (nếu có)

In [66]:
conn.execute("""
DELETE FROM gold.forecast_arima
""")

# 20. Ghi forecast_df lên MotherDuck

In [67]:
conn.register(
    "forecast_temp",
    forecast_df
)

conn.execute("""
INSERT INTO gold.forecast_arima
SELECT *
FROM forecast_temp
""")

# 21. Kiểm tra đã lưu chưa

In [68]:
conn.execute("""
SELECT *
FROM gold.forecast_arima
LIMIT 10
""").fetchdf()

        date commodity  actual_price  predicted_price
0 2023-01-01    coffee       2.62211          2.22929
1 2023-02-01    coffee       2.69114          2.22929
2 2023-03-01    coffee       2.60539          2.22929
3 2023-04-01    coffee       2.66971          2.22929
4 2023-05-01    coffee       2.85136          2.22929
5 2023-06-01    coffee       2.80040          2.22929
6 2023-07-01    coffee       2.79216          2.22929
7 2023-08-01    coffee       2.80283          2.22929
8 2023-09-01    coffee       2.61770          2.22929
9 2023-10-01    coffee       2.69743          2.22929

# 22. Lưu metric để so sánh với LSTM

In [69]:
metrics_df

  commodity arima_order      rmse       mae       mape
0    coffee   (0, 1, 0)  1.299288  1.112294  30.535434
1      rice   (0, 1, 0)  0.139201  0.137992  24.846247
2    pepper   (0, 1, 0)  0.601002  0.494289  10.868928

In [70]:
metrics_df.to_csv(
    "arima_metrics.csv",
    index=False
)